# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentreg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import traceback

class Ui_MainWindow(object):
    def studentregister(self):
        sno = self.number.text()
        sname = self.name.text()
        ssex = self.sex.currentText()
        psword = self.password.text()
        qq = self.QQnum.text()
        telnum = self.tel.text()
        dno = self.deptnum.text()
        clsno = self.classnum.text()
        try:
            conn = sqlite3.connect("school.db")
            cursor = conn.cursor()
            # 注意单双引号
            cursor.execute("PRAGMA foreign_keys = ON")
            cursor.execute('insert into student values(?,?,?,?,?,?,?,?)',(sno,sname,ssex,psword,qq,telnum,dno,clsno))
            # cursor.execute("select * from user")
            # print(cursor.fetchone())
            # print(cursor.fetchmany(100))
            conn.commit()
            cursor.close()
            conn.close()
            self.registerreact.setText("追加"+sname+"成功")
        except sqlite3.IntegrityError:
            traceback.print_exc()
            self.registerreact.setText("不满足完整性约束")
            conn.rollback()
            cursor.close()
            conn.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 323)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 30, 160, 204))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.number.setObjectName("number")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.number)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sex = QtWidgets.QComboBox(self.formLayoutWidget)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sex)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password)
        self.QQnum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.QQnum.setObjectName("QQnum")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.QQnum)
        self.tel = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tel.setObjectName("tel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tel)
        self.deptnum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.deptnum.setObjectName("deptnum")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.deptnum)
        self.classnum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.classnum.setObjectName("classnum")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.classnum)
        self.registerbutton = QtWidgets.QPushButton(self.centralwidget)
        self.registerbutton.setGeometry(QtCore.QRect(140, 240, 75, 23))
        self.registerbutton.setObjectName("registerbutton")
        self.registerbutton.clicked.connect(self.studentregister)
        self.registerreact = QtWidgets.QLabel(self.centralwidget)
        self.registerreact.setGeometry(QtCore.QRect(40, 240, 101, 31))
        self.registerreact.setObjectName("registerreact")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(240, 30, 160, 80))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.enrolldate = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.enrolldate.setObjectName("enrolldate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enrolldate)
        self.school = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.school.setObjectName("school")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.school)
        self.edulevel = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.edulevel.setObjectName("edulevel")
        self.edulevel.addItem("")
        self.edulevel.addItem("")
        self.edulevel.addItem("")
        self.edulevel.addItem("")
        self.edulevel.addItem("")
        self.edulevel.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edulevel)
        self.addedubutton = QtWidgets.QPushButton(self.centralwidget)
        self.addedubutton.setGeometry(QtCore.QRect(330, 120, 75, 23))
        self.addedubutton.setObjectName("addedubutton")
        self.edureaction = QtWidgets.QLabel(self.centralwidget)
        self.edureaction.setGeometry(QtCore.QRect(230, 120, 101, 31))
        self.edureaction.setObjectName("edureaction")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(240, 150, 160, 80))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.relationship = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.relationship.setObjectName("relationship")
        self.relationship.addItem("")
        self.relationship.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.relationship)
        self.parentname = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.parentname.setObjectName("parentname")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.parentname)
        self.parenttel = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.parenttel.setObjectName("parenttel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.parenttel)
        self.parentreaction = QtWidgets.QLabel(self.centralwidget)
        self.parentreaction.setGeometry(QtCore.QRect(230, 240, 101, 31))
        self.parentreaction.setObjectName("parentreaction")
        self.addedubutton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.addedubutton_2.setGeometry(QtCore.QRect(330, 240, 75, 23))
        self.addedubutton_2.setObjectName("addedubutton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def addeducation(self):
        sno = self.number.text()
        level = self.edulevel.currentText()
        schoolname = self.school.text()
        date = self.enrolldate.text()
        try:
            conn = sqlite3.connect("school.db")
            cursor = conn.cursor()
            # 注意单双引号
            cursor.execute("PRAGMA foreign_keys = ON")
            cursor.execute('insert into edu values(?,?,?,?)',(sno,level,schoolname,date))
            # cursor.execute("select * from user")
            # print(cursor.fetchone())
            # print(cursor.fetchmany(100))
            conn.commit()
            cursor.close()
            conn.close()
            self.edureaction.setText("追加"+schoolname+"成功")
        except sqlite3.IntegrityError:
            traceback.print_exc()
            self.edureaction.setText("不满足完整性约束")
            conn.rollback()
            cursor.close()
            conn.close()
    def addrelations(self):
        sno = self.number.text()
        pname = self.parentname.text()
        psex = self.relationship.currentText()
        ptel = self.parenttel.text()
        try:
            conn = sqlite3.connect("school.db")
            cursor = conn.cursor()
            # 注意单双引号
            cursor.execute("PRAGMA foreign_keys = ON")
            cursor.execute('insert into parents values(?,?,?,?)',(sno,pname,psex,ptel))
            # cursor.execute("select * from user")
            # print(cursor.fetchone())
            # print(cursor.fetchmany(100))
            conn.commit()
            cursor.close()
            conn.close()
            self.parentreaction.setText("追加"+pname+"成功")
        except sqlite3.IntegrityError:
            traceback.print_exc()
            self.parentreaction.setText("不满足完整性约束")
            conn.rollback()
            cursor.close()
            conn.close()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "学生学号"))
        self.label_2.setText(_translate("MainWindow", "学生姓名"))
        self.label_3.setText(_translate("MainWindow", "学生性别"))
        self.sex.setItemText(0, _translate("MainWindow", "男"))
        self.sex.setItemText(1, _translate("MainWindow", "女"))
        self.label_4.setText(_translate("MainWindow", "QQ号"))
        self.label_6.setText(_translate("MainWindow", "电话号码"))
        self.label_7.setText(_translate("MainWindow", "所属系号"))
        self.label_8.setText(_translate("MainWindow", "登录密码"))
        self.label_5.setText(_translate("MainWindow", "所属班号"))
        self.registerbutton.setText(_translate("MainWindow", "学生注册"))
        self.registerreact.setText(_translate("MainWindow", "学生注册->"))
        self.label_10.setText(_translate("MainWindow", "教育等级"))
        self.label_11.setText(_translate("MainWindow", "学校"))
        self.label_12.setText(_translate("MainWindow", "入学日期"))
        self.edulevel.setItemText(0, _translate("MainWindow", "小学"))
        self.edulevel.setItemText(1, _translate("MainWindow", "初中"))
        self.edulevel.setItemText(2, _translate("MainWindow", "高中"))
        self.edulevel.setItemText(3, _translate("MainWindow", "本科"))
        self.edulevel.setItemText(4, _translate("MainWindow", "研究生"))
        self.edulevel.setItemText(5, _translate("MainWindow", "博士"))
        self.addedubutton.setText(_translate("MainWindow", "添加教育经历"))
        self.addedubutton.clicked.connect(self.addeducation)
        self.edureaction.setText(_translate("MainWindow", "添加教育经历->"))
        self.label_14.setText(_translate("MainWindow", "亲属姓名"))
        self.label_15.setText(_translate("MainWindow", "关系"))
        self.label_16.setText(_translate("MainWindow", "亲属电话"))
        self.relationship.setItemText(0, _translate("MainWindow", "父"))
        self.relationship.setItemText(1, _translate("MainWindow", "母"))
        self.parentreaction.setText(_translate("MainWindow", "添加亲属->"))
        self.addedubutton_2.setText(_translate("MainWindow", "添加亲属"))
        self.addedubutton_2.clicked.connect(self.addrelations)

